"""initial schema

Revision ID: 438f5fb88d41
Revises:
Create Date: 2026-03-24 23:34:37.297654

"""

from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "438f5fb88d41"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("full_name", sa.String(), nullable=False),
        sa.Column("company_name", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("photo_url", sa.String(), nullable=True),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when the record was created.",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp of the last modification.",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("company_name"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "projects",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Unique identifier for the feature.",
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(length=100), nullable=True),
        sa.Column(
            "status",
            sa.String(),
            nullable=False,
        ),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when the record was created.",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp of the last modification.",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "layers",
        sa.Column(
            "id", sa.UUID(), nullable=False, comment="Unique identifier for the layer."
        ),
        sa.Column(
            "project_id",
            sa.UUID(),
            nullable=False,
            comment="Project this layer belongs to.",
        ),
        sa.Column(
            "created_by",
            sa.UUID(),
            nullable=False,
            comment="User who created this layer.",
        ),
        sa.Column(
            "name",
            sa.String(length=255),
            nullable=False,
            comment="Layer name visible in the side panel.",
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=True,
            comment="Optional description of what this layer contains.",
        ),
        sa.Column(
            "geometry_type",
            sa.String(),
            nullable=False,
            comment="Type of geometry stored in this layer. Cannot be changed after creation.",
        ),
        sa.Column(
            "style",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Visual configuration in JSONB: fill_color, stroke_color, opacity, point_radius, stroke_width.",
        ),
        sa.Column(
            "filters",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Active filters on layer attributes. Persisted so the map restores the same filter state on reopen.",
        ),
        sa.Column(
            "attribute_schema",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Dynamic schema of feature attributes. Auto-filled on file import from column names. Used by frontend to build filter forms without scanning all features.",
        ),
        sa.Column(
            "visible",
            sa.Boolean(),
            nullable=False,
            comment="Whether the layer is visible on the map. Toggled by the user from the side panel.",
        ),
        sa.Column(
            "z_index",
            sa.Integer(),
            nullable=False,
            comment="Stacking order on the map. Higher value = rendered on top of other layers.",
        ),
        sa.Column(
            "status",
            sa.String(),
            nullable=False,
            comment="Logical delete flag. Deleted layers are not physically removed from the database.",
        ),
        sa.Column(
            "feature_count",
            sa.Integer(),
            nullable=False,
            comment="Count of active features in this layer. Kept up to date by a PostgreSQL trigger on the features table.",
        ),
        sa.Column(
            "is_derived",
            sa.Boolean(),
            nullable=False,
            comment="True if this layer was generated by a geoprocess. False if manually created or imported.",
        ),
        sa.Column(
            "parent_layer_id",
            sa.UUID(),
            nullable=True,
            comment="[Geoprocess] Reference to the source layer this layer was derived from. Only set when is_derived is True.",
        ),
        sa.Column(
            "geoprocess_type",
            sa.String(length=50),
            nullable=True,
            comment="[Geoprocess] Type of operation that generated this layer: buffer, intersection, union, difference, dissolve, spatial_join, centroid, route_generation.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when the record was created.",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp of the last modification.",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_layer_id"],
            ["layers.id"],
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "features",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Unique identifier for the feature.",
        ),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
            comment="Native PostGIS geometry in WGS84.",
        ),
        sa.Column(
            "attributes",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Feature attributes as key-value pairs. Flexible schema per layer.",
        ),
        sa.Column(
            "status",
            sa.String(),
            nullable=False,
            comment="Logical delete flag.",
        ),
        sa.Column(
            "layer_id",
            sa.UUID(),
            nullable=False,
            comment="Layer this feature belongs to.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when the record was created.",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp of the last modification.",
        ),
        sa.ForeignKeyConstraint(["layer_id"], ["layers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("features")
    op.drop_table("layers")
    op.drop_table("projects")
    op.drop_table("users")
    # ### end Alembic commands ###
