"""fix_enums_standard

Revision ID: 97ceff422a5e
Revises: 438f5fb88d41
Create Date: 2026-03-25 00:14:18.242367

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "97ceff422a5e"
down_revision: Union[str, Sequence[str], None] = "438f5fb88d41"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "layers",
        "status",
        existing_type=sa.VARCHAR(),
        comment="Status of the layer.",
        existing_comment="Logical delete flag. Deleted layers are not physically removed from the database.",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "layers",
        "status",
        existing_type=sa.VARCHAR(),
        comment="Logical delete flag. Deleted layers are not physically removed from the database.",
        existing_comment="Status of the layer.",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
