"""make created_by nullable in layers

Revision ID: ecc74dbab301
Revises: 0124b3271523
Create Date: 2026-05-04 17:06:32.761219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecc74dbab301'
down_revision: Union[str, Sequence[str], None] = '0124b3271523'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('layers', 'created_by',
               existing_type=sa.UUID(),
               nullable=True,
               existing_comment='User who created this layer.')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('layers', 'created_by',
               existing_type=sa.UUID(),
               nullable=False,
               existing_comment='User who created this layer.')
    # ### end Alembic commands ###
