"""add new columns

Revision ID: f2b9ac039ca0
Revises: 97ceff422a5e
Create Date: 2026-04-02 20:25:14.327130

"""
from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2b9ac039ca0'
down_revision: Union[str, Sequence[str], None] = '97ceff422a5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('layers', sa.Column('bbox', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True, comment='Bounding box of the layer for fast map zooming.'))
    op.add_column('layers', sa.Column('srid', sa.Integer(), nullable=False, comment='Spatial reference system of the original data.'))
    op.drop_column('layers', 'feature_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('layers', sa.Column('feature_count', sa.INTEGER(), autoincrement=False, nullable=False, comment='Count of active features in this layer. Kept up to date by a PostgreSQL trigger on the features table.'))
    op.drop_index('idx_layers_bbox', table_name='layers', postgresql_using='gist')
    op.drop_column('layers', 'srid')
    op.drop_column('layers', 'bbox')
    # ### end Alembic commands ###
