import enum
from typing import TYPE_CHECKING, Optional
from app.database.db import Base
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy import String, Boolean, Integer, ForeignKey, Enum as SqlEnum, Text
import uuid


if TYPE_CHECKING:
    from app.models import Project, Feature


class GeometryType(enum.Enum):
    POINT = "point"
    LINESTRING = "linestring"
    POLYGON = "polygon"


class LayerStatus(enum.Enum):
    ACTIVE = "active"
    DELETED = "deleted"


class Layer(Base):
    __tablename__ = "layers"

    # ── Identity ──────────────────────────────────────────────
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        comment="Unique identifier for the layer.",
    )

    # ── Foreign Keys ──────────────────────────────────────────
    project_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("projects.id", ondelete="CASCADE"),
        nullable=False,
        comment="Project this layer belongs to.",
    )
    created_by: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id"),
        nullable=False,
        comment="User who created this layer.",
    )

    # ── Basic Info ────────────────────────────────────────────
    name: Mapped[str] = mapped_column(
        String(255), nullable=False, comment="Layer name visible in the side panel."
    )
    description: Mapped[Optional[str]] = mapped_column(
        Text, nullable=True, comment="Optional description of what this layer contains."
    )
    geometry_type: Mapped[GeometryType] = mapped_column(
        SqlEnum(
            GeometryType,
            name="geometrytype",
            values_callable=lambda x: [e.value for e in x],
            native_enum=False,
        ),
        nullable=False,
        comment="Type of geometry stored in this layer. Cannot be changed after creation.",
    )

    # ── Visual Config ─────────────────────────────────────────
    style: Mapped[Optional[dict]] = mapped_column(
        JSONB,
        nullable=True,
        comment="Visual configuration in JSONB: fill_color, stroke_color, opacity, point_radius, stroke_width.",
    )
    filters: Mapped[Optional[dict]] = mapped_column(
        JSONB,
        nullable=True,
        comment="Active filters on layer attributes. Persisted so the map restores the same filter state on reopen.",
    )
    attribute_schema: Mapped[Optional[dict]] = mapped_column(
        JSONB,
        nullable=True,
        comment="Dynamic schema of feature attributes. Auto-filled on file import from column names. Used by frontend to build filter forms without scanning all features.",
    )
    status: Mapped[LayerStatus] = mapped_column(
        SqlEnum(
            LayerStatus,
            name="layerstatus",
            values_callable=lambda x: [e.value for e in x],
            native_enum=False,
        ),
        default=LayerStatus.ACTIVE,
        nullable=False,
        comment="Status of the layer.",
    )
    visible: Mapped[bool] = mapped_column(
        Boolean,
        default=True,
        nullable=False,
        comment="Whether the layer is visible on the map. Toggled by the user from the side panel.",
    )
    z_index: Mapped[int] = mapped_column(
        Integer,
        default=0,
        nullable=False,
        comment="Stacking order on the map. Higher value = rendered on top of other layers.",
    )
    feature_count: Mapped[int] = mapped_column(
        Integer,
        default=0,
        nullable=False,
        comment="Count of active features in this layer. Kept up to date by a PostgreSQL trigger on the features table.",
    )

    # ── Geoprocess Fields ─────────────────────────────────────
    # These fields are only populated when the layer was generated
    # by a geoprocess operation (is_derived = True).
    # They are null for manually created or imported layers.

    is_derived: Mapped[bool] = mapped_column(
        Boolean,
        default=False,
        nullable=False,
        comment="True if this layer was generated by a geoprocess. False if manually created or imported.",
    )
    parent_layer_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("layers.id"),
        nullable=True,
        comment="[Geoprocess] Reference to the source layer this layer was derived from. Only set when is_derived is True.",
    )
    geoprocess_type: Mapped[Optional[str]] = mapped_column(
        String(50),
        nullable=True,
        comment="[Geoprocess] Type of operation that generated this layer: buffer, intersection, union, difference, dissolve, spatial_join, centroid, route_generation.",
    )

    # ── Relationships ─────────────────────────────────────────
    project: Mapped["Project"] = relationship("Project", back_populates="layers")
    features: Mapped[list["Feature"]] = relationship(
        "Feature", back_populates="layer", cascade="all, delete-orphan"
    )

    # Self-referential: a derived layer points to its source layer
    parent_layer: Mapped[Optional["Layer"]] = relationship(
        "Layer", remote_side=[id], back_populates="derived_layers"
    )
    derived_layers: Mapped[list["Layer"]] = relationship(
        "Layer", back_populates="parent_layer"
    )
